
[username]
disabled = false
show_always = true

[memory_usage]
disabled = true
threshold = 0
format = "via $symbol [${ram} | ${ram_pct}]($style) "

[hostname]
disabled = false
ssh_only = false

[time]
use_12hr = true
disabled = false

[env_var]
variable = 'STARSHIP_SHELL'
style = 'cyan'

[character]
error_symbol = "[](bold red) "

[status]
format = '[$status]($style) '
disabled = false

