assert(vim.g.jerry_enabled and vim.g.jerry_legacy)
assert(vim.g.perforce_enabled)
assert(package.loaded['jerry.integrations.home_manager'])
assert(package.loaded['jerry.lsp.config'])
assert(package.loaded['telescope'])
assert(package.loaded['blink.cmp'])
assert(not package.loaded['lazy'] and not package.loaded['mason'])
assert(vim.g.colors_name == 'gruvbox-material')
assert(vim.fn.exists(':LuaFormat') == 2 and vim.fn.exists(':LuaLint') == 2)
assert(vim.fn.maparg(' b', 'n') ~= '')
vim.cmd.edit('/root/workspace/format.lua')
vim.api.nvim_buf_set_lines(0, 0, -1, false, { 'local x={a=1}', 'return x' })
vim.cmd.write()
assert(vim.api.nvim_buf_get_lines(0, 0, 1, false)[1] ~= 'local x={a=1}', 'Home Manager format on save failed')
assert(vim.wait(20000, function()
  return #vim.lsp.get_clients({ bufnr = 0, name = 'lua_ls' }) > 0
end, 100), 'Home Manager Lua language server did not attach')
vim.api.nvim_buf_set_lines(0, 0, -1, false, { 'this_global_is_undefined()' })
vim.cmd.write()
require('jerry.lua-tools').lint()
local namespace = vim.api.nvim_create_namespace('jerry_luacheck')
assert(vim.wait(10000, function()
  return #vim.diagnostic.get(0, { namespace = namespace }) > 0
end, 100), 'Home Manager Luacheck did not publish diagnostics')
vim.bo.modified = false
vim.cmd.edit('/root/workspace/journal.md')
assert(vim.b.jerry_markdown_setup_done and vim.b.jerry_markdown_links_setup_done)
assert(vim.v.errmsg == '', vim.v.errmsg)
vim.fn.writefile({ 'Real Home Manager integration checks passed' }, '/tmp/jerry-home-manager-result')
